### ISSUE TITLE
"pip3 install --user" fails

### ISSUE THREAD

**Issue by paulmadejong** [space-physics/WMM2015#1]
When installing wmm2015 on my machine (non-root, no sudo privileges) for the user account, it fails with the following error:
```bash
[user@pcxx /home/user]$ pip3 install --user wmm2015
Collecting wmm2015
  Using cached https://files.pythonhosted.org/packages/23/57/699482c68aaad29dbee9b410d2eccd643823dfcce598700fcef70ceb56f2/wmm2015-0.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/wmm2015.egg-info
    writing pip-egg-info/wmm2015.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/wmm2015.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/wmm2015.egg-info/entry_points.txt
    writing requirements to pip-egg-info/wmm2015.egg-info/requires.txt
    writing top-level names to pip-egg-info/wmm2015.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/wmm2015.egg-info/SOURCES.txt'
    warning: Failed to find the configured license file 'LICENSE'
    reading manifest file 'pip-egg-info/wmm2015.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/wmm2015.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-p2v6071y/wmm2015/setup.py", line 12, in <module>
        subprocess.check_call(['cmake', '../src'], cwd='bin')
      File "/usr/lib64/python3.7/subprocess.py", line 342, in check_call
        retcode = call(*popenargs, **kwargs)
      File "/usr/lib64/python3.7/subprocess.py", line 323, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/usr/lib64/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/lib64/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'bin': 'bin'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-p2v6071y/wmm2015/
```

**Comment by scivision** [comment]
This was a typo and was fixed. We also add Meson as an alternative to CMake
