### ISSUE TITLE
python3 -m pip install wwm2015 fails

### ISSUE THREAD

**Issue by titulebolide** [space-physics/WMM2015#2]
Hi! FIrst off, thank you for this useful library!
I tried to install it on a clean Debian 9 distro, with python version 3.7.4.
My compilator must be GCC since I work on linux.
Running `python3 -m pip install wwm2015 fails` as sudo sends:
```bash
Collecting wmm2015
  Downloading https://files.pythonhosted.org/packages/23/57/699482c68aaad29dbee9b410d2eccd643823dfcce598700fcef70ceb56f2/wmm2015-0.9.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lm_ugkic/wmm2015/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lm_ugkic/wmm2015/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-lm_ugkic/wmm2015/pip-egg-info
         cwd: /tmp/pip-install-lm_ugkic/wmm2015/
    Complete output (24 lines):
    running egg_info
    creating /tmp/pip-install-lm_ugkic/wmm2015/pip-egg-info/wmm2015.egg-info
    writing /tmp/pip-install-lm_ugkic/wmm2015/pip-egg-info/wmm2015.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-lm_ugkic/wmm2015/pip-egg-info/wmm2015.egg-info/dependency_links.txt
    writing entry points to /tmp/pip-install-lm_ugkic/wmm2015/pip-egg-info/wmm2015.egg-info/entry_points.txt
    writing requirements to /tmp/pip-install-lm_ugkic/wmm2015/pip-egg-info/wmm2015.egg-info/requires.txt
    writing top-level names to /tmp/pip-install-lm_ugkic/wmm2015/pip-egg-info/wmm2015.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-lm_ugkic/wmm2015/pip-egg-info/wmm2015.egg-info/SOURCES.txt'
    warning: Failed to find the configured license file 'LICENSE'
    reading manifest file '/tmp/pip-install-lm_ugkic/wmm2015/pip-egg-info/wmm2015.egg-info/SOURCES.txt'
    writing manifest file '/tmp/pip-install-lm_ugkic/wmm2015/pip-egg-info/wmm2015.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lm_ugkic/wmm2015/setup.py", line 12, in <module>
        subprocess.check_call(['cmake', '../src'], cwd='bin')
      File "/usr/local/lib/python3.7/subprocess.py", line 342, in check_call
        retcode = call(*popenargs, **kwargs)
      File "/usr/local/lib/python3.7/subprocess.py", line 323, in call
        with Popen(*popenargs, **kwargs) as p:
      File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
        restore_signals, start_new_session)
      File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'bin': 'bin'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Thank you in advance!

**Comment by scivision** [comment]
Yes this was a bug in the old setup.py, this was fixed in v1.0.0

Thanks for reporting this issue!

**Comment by titulebolide** [comment]
Thanks!
It worked -practically- like a charm. Maybe the installation procedure would wand to update ninja so it is >= 1.5.0. (I don't know how it works, but ninja isn't actually updated and does not seems to be up to date even on python3.8)
Again, thanks!

**Comment by scivision** [comment]
OK thanks that is an excellent point, I need to add `ninja` to the prerequisites that pip automatically installs.

**Comment by scivision** [comment]
Ninja was added as an auto-installed prereq in v1.0.2, thanks again.
